version: "3"

services:
  backend:
    build:
      context: ./backend
      args:
        WORKDIR: /app
    image: szsebestyen/ttv-chat-search-backend
    depends_on:
      - mongo
      - chat-downloader
    environment:
      - DB_CONNECTION
      - CHAT_DOWNLOADER_HOST
      - PORT=$BACKEND_PORT
    ports:
      - $BACKEND_PORT:$BACKEND_PORT
    networks:
      - the-network
    volumes:
      - ./backend:/app/

  chat-downloader:
    build:
      context: ./chat-downloader
      args:
        WORKDIR: /app
    image: szsebestyen/ttv-chat-search-chat-downloader
    depends_on:
      - mongo
    environment:
      - DB_CONNECTION
      - TWITCH_CLIENT_ID
      - TWITCH_CLIENT_SECRET
      - TWITCH_ACCESS_TOKEN
      - PORT=$CHAT_DOWNLOADER_PORT
    ports:
      - $CHAT_DOWNLOADER_PORT:$CHAT_DOWNLOADER_PORT
    networks:
      - the-network
    volumes:
      - ./chat-downloader:/app/

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    image: szsebestyen/ttv-chat-search-frontend
    depends_on:
      - backend
    ports:
      - 3000:3000
    networks:
      - the-network
    volumes:
      - ./frontend:/app/

  mongo:
    image: mongo:4.4.6
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    networks:
      - the-network

networks:
  the-network:
    driver: bridge
volumes:
  mongo-data:
    driver: local
